sonar.projectKey=griswaldbrooks_worklog
sonar.organization=griswaldbrooks
sonar.projectName=worklog
sonar.projectVersion=1.0.0
sonar.sources=src/
sonar.coverageReportPaths=sonar-coverage.xml
sonar.exclusions=target/**,tests/**
sonar.sourceEncoding=UTF-8
